<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CountriesTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {

        \DB::table('countries')->delete();

        \DB::table('countries')->insert([
            0 => [
                'id' => 1,
                'name' => 'Turkey',
                'official_name' => 'Republic of Türkiye',
                'native_name' => 'Türkiye',
                'iso2' => 'TR',
                'iso3' => 'TUR',
                'numeric_code' => '792',
                'phone_code' => '+90',
                'phone_root' => null,
                'phone_suffixes' => null,
                'currency_code' => 'TRY',
                'currency_name' => 'Turkish lira',
                'currency_symbol' => '₺',
                'region' => 'Asia',
                'subregion' => 'Western Asia',
                'capital' => 'Ankara',
                'continents' => null,
                'timezones' => null,
                'latitude' => null,
                'longitude' => null,
                'languages' => null,
                'flag_emoji' => '🇹🇷',
                'flag_png' => null,
                'flag_svg' => null,
                'population' => 0,
                'is_active' => 1,
                'sort_order' => 1,
                'extra_data' => null,
                'created_by' => null,
                'updated_by' => null,
                'created_at' => '2026-04-17 10:47:08',
                'updated_at' => '2026-04-17 10:47:08',
                'deleted_at' => null,
            ],
            1 => [
                'id' => 2,
                'name' => 'Northern Cyprus',
                'official_name' => 'Turkish Republic of Northern Cyprus',
                'native_name' => 'Kuzey Kıbrıs',
                'iso2' => 'CY',
                'iso3' => 'CYP',
                'numeric_code' => '196',
                'phone_code' => '+90',
                'phone_root' => null,
                'phone_suffixes' => null,
                'currency_code' => 'TRY',
                'currency_name' => 'Turkish lira',
                'currency_symbol' => '₺',
                'region' => 'Europe',
                'subregion' => 'Southern Europe',
                'capital' => 'Lefkoşa',
                'continents' => null,
                'timezones' => null,
                'latitude' => null,
                'longitude' => null,
                'languages' => null,
                'flag_emoji' => '🇨🇾',
                'flag_png' => null,
                'flag_svg' => null,
                'population' => 0,
                'is_active' => 1,
                'sort_order' => 2,
                'extra_data' => null,
                'created_by' => null,
                'updated_by' => null,
                'created_at' => '2026-04-17 10:47:08',
                'updated_at' => '2026-04-17 10:47:08',
                'deleted_at' => null,
            ],
            2 => [
                'id' => 3,
                'name' => 'Germany',
                'official_name' => 'Federal Republic of Germany',
                'native_name' => 'Deutschland',
                'iso2' => 'DE',
                'iso3' => 'DEU',
                'numeric_code' => '276',
                'phone_code' => '+49',
                'phone_root' => null,
                'phone_suffixes' => null,
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'currency_symbol' => '€',
                'region' => 'Europe',
                'subregion' => 'Western Europe',
                'capital' => 'Berlin',
                'continents' => null,
                'timezones' => null,
                'latitude' => null,
                'longitude' => null,
                'languages' => null,
                'flag_emoji' => '🇩🇪',
                'flag_png' => null,
                'flag_svg' => null,
                'population' => 0,
                'is_active' => 1,
                'sort_order' => 3,
                'extra_data' => null,
                'created_by' => null,
                'updated_by' => null,
                'created_at' => '2026-04-17 10:47:08',
                'updated_at' => '2026-04-17 10:47:08',
                'deleted_at' => null,
            ],
            3 => [
                'id' => 4,
                'name' => 'United Kingdom',
                'official_name' => 'United Kingdom of Great Britain and Northern Ireland',
                'native_name' => 'United Kingdom',
                'iso2' => 'GB',
                'iso3' => 'GBR',
                'numeric_code' => '826',
                'phone_code' => '+44',
                'phone_root' => null,
                'phone_suffixes' => null,
                'currency_code' => 'GBP',
                'currency_name' => 'British pound',
                'currency_symbol' => '£',
                'region' => 'Europe',
                'subregion' => 'Northern Europe',
                'capital' => 'London',
                'continents' => null,
                'timezones' => null,
                'latitude' => null,
                'longitude' => null,
                'languages' => null,
                'flag_emoji' => '🇬🇧',
                'flag_png' => null,
                'flag_svg' => null,
                'population' => 0,
                'is_active' => 1,
                'sort_order' => 4,
                'extra_data' => null,
                'created_by' => null,
                'updated_by' => null,
                'created_at' => '2026-04-17 10:47:08',
                'updated_at' => '2026-04-17 10:47:08',
                'deleted_at' => null,
            ],
            4 => [
                'id' => 5,
                'name' => 'Netherlands',
                'official_name' => 'Kingdom of the Netherlands',
                'native_name' => 'Nederland',
                'iso2' => 'NL',
                'iso3' => 'NLD',
                'numeric_code' => '528',
                'phone_code' => '+31',
                'phone_root' => null,
                'phone_suffixes' => null,
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'currency_symbol' => '€',
                'region' => 'Europe',
                'subregion' => 'Western Europe',
                'capital' => 'Amsterdam',
                'continents' => null,
                'timezones' => null,
                'latitude' => null,
                'longitude' => null,
                'languages' => null,
                'flag_emoji' => '🇳🇱',
                'flag_png' => null,
                'flag_svg' => null,
                'population' => 0,
                'is_active' => 1,
                'sort_order' => 5,
                'extra_data' => null,
                'created_by' => null,
                'updated_by' => null,
                'created_at' => '2026-04-17 10:47:08',
                'updated_at' => '2026-04-17 10:47:08',
                'deleted_at' => null,
            ],
            5 => [
                'id' => 6,
                'name' => 'United States',
                'official_name' => 'United States of America',
                'native_name' => 'United States',
                'iso2' => 'US',
                'iso3' => 'USA',
                'numeric_code' => '840',
                'phone_code' => '+1',
                'phone_root' => null,
                'phone_suffixes' => null,
                'currency_code' => 'USD',
                'currency_name' => 'US dollar',
                'currency_symbol' => '$',
                'region' => 'Americas',
                'subregion' => 'North America',
                'capital' => 'Washington D.C.',
                'continents' => null,
                'timezones' => null,
                'latitude' => null,
                'longitude' => null,
                'languages' => null,
                'flag_emoji' => '🇺🇸',
                'flag_png' => null,
                'flag_svg' => null,
                'population' => 0,
                'is_active' => 1,
                'sort_order' => 6,
                'extra_data' => null,
                'created_by' => null,
                'updated_by' => null,
                'created_at' => '2026-04-17 10:47:08',
                'updated_at' => '2026-04-17 10:47:08',
                'deleted_at' => null,
            ],
        ]);

    }
}
